### ISSUE TITLE
/usr/bin/dist-clang/clang++ -print-prog-name=ld incorrect result

### ISSUE THREAD

**Issue by zeac** [abyss7/dist-clang#42]
Without setting DC_LOG_LEVELS and DC_LOG_ERROR_MARK env variables client writes
```
No Clang commands found
Failed to parse driver arguments - see errors above
/usr/bin/ld
```
to stdout that leads to errors when using within scripts.

**Comment by abyss7** [comment]
Should be solved in master with 7ca8d00c7c4a4797edd79837230ca40c7b54f46f
